import {
    Button,
    Slider,
    AutoComplete,
    Badge,
    Alert,
    ButtonGroup,
    Label,
    FormControl,
    FormGroup,
    Form,
    InputGroup,
    InputNumber,
    Checkbox,
    Pagination,
    ProgressBar,
    Radio,
    Switch,
    Tooltip,
    Con,
    Row,
    Col,
    Dropdown,
    Panel,
    PanelGroup,
    Transition,
    Select,
    Animate,
    Icon,
    Menu,
    Breadcrumb,
    Upload,
    Tile,
    Navbar,
    Message,
    Popconfirm,
    Modal,
    Tabs,
    Cascader,
    Loading,
    Table,
    Tree,
    Clipboard,
    Rate,
    Step,
    Timeline,
    Transfer,
    BackTop,
    Collapse,
    LoadingState,
    Locale,
    Popover,
    Anchor,
    Tag,
    ColorPicker,
    SearchPanel,
    Affix,
    Drawer,
    TreeSelect
} from 'tinper-bee';

import DatePicker from 'bee-datepicker';
import Timepicker from 'bee-timepicker';
import PageLayout from 'bee-page-layout';

export default {
    "PageLayout":PageLayout ,
    "PageLayout.Header":PageLayout.Header,
    "PageLayout.Content": PageLayout.Content,
    "PageLayout.SearchArea": PageLayout.SearchArea,
    "PageLayout.TableContent": PageLayout.TableContent,
    "PageLayout.LeftContent": PageLayout.LeftContent,
    "PageLayout.RightContent": PageLayout.RightContent,
    Slider: Slider,
    AutoComplete: AutoComplete,
    Button: Button,
    Badge: Badge,
    Alert: Alert,
    ButtonGroup: ButtonGroup,
    Label: Label,
    FormControl: FormControl,
    FormGroup: FormGroup,
    Form: Form,
    InputGroup: InputGroup,
    InputNumber: InputNumber,
    Checkbox: Checkbox,
    Pagination: Pagination,
    ProgressBar: ProgressBar,
    Radio: Radio,
    Switch: Switch,
    Tooltip: Tooltip,
    Con: Con,
    Row: Row,
    Col: Col,
    Dropdown: Dropdown,
    Panel: Panel,
    PanelGroup: PanelGroup,
    Transition: Transition,
    Select: Select,
    Animate: Animate,
    Icon: Icon,
    "Menu": Menu,
    "Menu.Item": Menu.Item,
    "Menu.SubMenu": Menu.SubMenu,
    "Menu.ItemGroup": Menu.ItemGroup,
    "Breadcrumb": Breadcrumb,
    "Breadcrumb.Item": Breadcrumb.Item,
    Upload: Upload,
    Tile: Tile,
    "Navbar": Navbar,
    "Navbar.Item": Navbar.Item,
    "Navbar.Header": Navbar.Header,
    "Navbar.Collapse": Navbar.Collapse,
    "Navbar.Brand": Navbar.Brand,
    "Navbar.Nav": Navbar.Nav,
    "Navbar.Toggle": Navbar.Toggle,
    Message: Message,
    Notification: Notification,
    Popconfirm: Popconfirm,
    Modal: Modal,
    Tabs: Tabs,
    Cascader: Cascader,
    Loading: Loading,
    Table: Table,
    Tree: Tree,
    Clipboard: Clipboard,
    Rate: Rate,
    "Step": Step,
    "Step.Steps": Step.Steps,
    Timeline: Timeline,
    Transfer: Transfer,
    BackTop: BackTop,
    Collapse: Collapse,
    LoadingState: LoadingState,
    Locale: Locale,
    Popover: Popover,
    Anchor:Anchor,
    Tag: Tag,
    ColorPicker: ColorPicker,
    SearchPanel: SearchPanel,
    Affix:Affix,
    Drawer:Drawer,
    TreeSelect:TreeSelect,
    DatePicker:DatePicker,
    Timepicker:Timepicker
};